"""Research Report Generator — produces readable Markdown research reports.

Usage:
    from workspace.research_report import generate_research_report
    md = generate_research_report()  # returns markdown string + saves to reports/
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parents[1]


def generate_research_report(
    *,
    title: str = "Daily Research Report",
    output_dir: Optional[str | Path] = None,
) -> str:
    """Generate a comprehensive Markdown research report."""
    from workspace.strategy_lifecycle import LifecycleManager, StrategyState
    from workspace.tracker import list_experiments, query_best
    from workspace.performance_monitor import PerformanceMonitor

    lm = LifecycleManager()
    pm = PerformanceMonitor()
    exps = list_experiments()
    summary = lm.summary()
    now = datetime.now(timezone.utc)

    md = f"""# {title}

**Generated:** {now.strftime('%Y-%m-%d %H:%M UTC')}

---

## 1. Strategy Portfolio Overview

| State | Count | Strategies |
|-------|-------|------------|
"""
    for state in ["active", "paper", "validated", "discovered", "retired"]:
        names = [s["name"] for s in summary["strategies"] if s["state"] == state]
        if names:
            md += f"| {state.upper()} | {len(names)} | {', '.join(names)} |\n"

    md += f"\n**Total: {summary['total']} strategies**\n"

    # Active strategies detail
    active = lm.list_by_state(StrategyState.ACTIVE)
    if active:
        md += "\n## 2. Active Strategies Performance\n\n"
        for s in active:
            config = s.get("config", {})
            sharpes = s.get("rolling_sharpe", [])
            paper_pnl = s.get("paper_pnl", [])
            md += f"### {s['name']}\n"
            md += f"- **Type:** {s.get('type', '?')}\n"
            if config.get("pair_a"):
                md += f"- **Pair:** {config['pair_a']} / {config['pair_b']}\n"
            if config.get("mean_profit"):
                md += f"- **Expected Mean Profit:** {config['mean_profit']:+.2f}%\n"
            md += f"- **Active Days:** {s.get('active_days', 0)}\n"
            if sharpes:
                import numpy as np
                md += f"- **Rolling Sharpe:** {np.mean(sharpes[-5:]):+.2f} (last 5 days)\n"
            if paper_pnl:
                md += f"- **Paper PnL History:** {', '.join(f'{p:+.2f}%' for p in paper_pnl[-7:])}\n"
            md += "\n"

    # Paper strategies
    paper = lm.list_by_state(StrategyState.PAPER)
    if paper:
        md += "\n## 3. Paper Trading Pool\n\n"
        md += "| Strategy | Days | Cumulative PnL | Status |\n"
        md += "|----------|------|----------------|--------|\n"
        for s in paper:
            pnl = s.get("paper_pnl", [])
            cum = sum(pnl) if pnl else 0
            status = "✅ profitable" if cum > 0 else "❌ losing"
            md += f"| {s['name']} | {s.get('paper_days', 0)} | {cum:+.2f}% | {status} |\n"

    # Health check
    md += "\n## 4. Health Check\n\n"
    health = pm.daily_check()
    md += f"- **Healthy:** {health.get('healthy', 0)} strategies\n"
    md += f"- **Issues:** {len(health.get('issues', []))}\n"
    for issue in health.get("issues", [])[:5]:
        md += f"  - ⚠️ {issue.get('strategy', '?')}: {', '.join(issue.get('details', []))}\n"

    # Experiment summary
    md += "\n## 5. Experiment Summary\n\n"
    md += f"- **Total experiments:** {len(exps)}\n"
    best = query_best("sharpe", 5)
    if best:
        md += "\n**Top 5 by Sharpe:**\n\n"
        md += "| # | Strategy | Sharpe | Profit | Trades |\n"
        md += "|---|----------|--------|--------|--------|\n"
        for i, e in enumerate(best, 1):
            m = e["metrics"]
            md += f"| {i} | {e['strategy_name']} | {m.get('sharpe', 0):+.2f} | {m.get('profit_pct', 0):+.2f}% | {m.get('trades', 0)} |\n"

    # Recommendations
    md += "\n## 6. Recommendations\n\n"
    by_state = summary.get("by_state", {})
    if by_state.get("paper", 0) == 0 and by_state.get("active", 0) == 0:
        md += "- 🔴 No strategies active — run discovery cycle\n"
    if len(health.get("issues", [])) > 0:
        md += f"- ⚠️ {len(health['issues'])} health issues — review pair stability\n"
    if by_state.get("discovered", 0) > 3:
        md += f"- 📋 {by_state['discovered']} strategies pending validation — run gate_pipeline\n"
    if by_state.get("paper", 0) > 0:
        md += "- 📊 Paper strategies active — check daily PnL\n"
    if by_state.get("active", 0) > 0:
        md += "- ✅ Active strategies running — monitor rolling Sharpe\n"

    md += f"\n---\n*Generated by Agent Market Research System*\n"

    # Save
    if output_dir is None:
        output_dir = ROOT / "workspace" / "reports"
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"report_{now.strftime('%Y%m%d_%H%M')}.md"
    path.write_text(md, encoding="utf-8")

    return md


__all__ = ["generate_research_report"]
